var facts = [
  {year:1066, event:"The Battle of Hastings."},
  {year:1206, event:"Genghis Khan becomes the sole ruler of the Mongol plains."},
  {year:1254, event:"Marco Polo is born in Venice, Italy."},
  {year:1415, event:"The Battle of Agincourt."},
  {year:1431, event:"Joan of Arc is executed by burning."},
  {year:1440, event:"Johannes Gutenberg invents the printing press."},
  {year:1487, event:"The House of Lancaster defeats the House of York in the War of the Roses."},
  {year:1492, event:"Christopher Columbus sails the ocean blue."},
  {year:1503, event:"Leonardo da Vinci paints the Mona Lisa."},
  {year:1512, event:"Michelangelo finishes painting the cieling of the Sistine Chapel."},
  {year:1517, event:"Martin Luther posts his 95 Theses."},
  {year:1519, event:"Hernan Cortes lands in Yucatan to conquer the Aztec Empire."},
  {year:1529, event:"The Siege of Vienna."},
  {year:1529, event:"Francisco Pizarro receives royal approval to conquer the Inca Empire."},
  {year:1588, event:"England defeats the Spanish Armada."},
  {year:1597, event:"William Shakespeare publishes Romeo and Juliet."},
  {year:1605, event:"Guy Fawkes attempts his gunpowder treason."},
  {year:1607, event:"The first permanent English settlement of Jamestown is established in America."},
  {year:1618, event:"The Defenestration of Prague."},
  {year:1642, event:"The English Civil War begins."},
  {year:1653, event:"Oliver Cromwell becomes Lord Protector of England."},
  {year:1682, event:"Versailles becomes the seat of power for the French monarchy."},
  {year:1746, event:"The Battle of Culloden Moor."},
  {year:1762, event:"Catherine the Great becomes Empress of Russia."},
  {year:1776, event:"Adam Smith publishes The Wealth of Nations."},
  {year:1781, event:"The Siege of Yorktown."},
  {year:1788, event:"The United States Constitution is ratified."},
  {year:1789, event:"The Storming of the Bastille."},
  {year:1805, event:"The Battle of Trafalgar."},
  {year:1807, event:"America and Britain outlaw the slave trade."},
  {year:1815, event:"The Battle of Waterloo."},
  {year:1848, event:"Karl Marx and Friedrich Engels publish The Communist Manifesto."},
  {year:1859, event:"Charles Darwin publishes On the Origin of Species."},
  {year:1862, event:"The Battle of Antietam."},
  {year:1876, event:"Alexander Graham Bell patents the telephone."},
  {year:1879, event:"Thomas Edison creates the first light bulb."},
  {year:1914, event:"Archduke Franz Ferdinand is assassinated."},
  {year:1928, event:"Alexander Fleming discovers Penicillin in a Petri dish."},
  {year:1940, event:"The Battle of Britain."},
  {year:1968, event:"The Tet Offensive."},
];
